dbdemos_dbt_c360:
  target: databricks_job
  outputs:
    databricks_job:
      type: databricks
      method: http
      catalog: "firasf_catalog"
      schema: "dbt"
      host: "e2-demo-field-eng.cloud.databricks.com"
      http_path: "sql/protocolv1/o/1444828305810485/0601-182128-dcbte59m"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"


